# Site settings
title: fleet commander
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://fleet-commander.org" # the base hostname & protocol for your site

permalink: /:title/

# Build settings
markdown: kramdown
